9 Mar 2016 07:46

/(A radical redo of org-pm, for latex and tiddlywiki)./

Publish an org-mode file or subtree: 

1. As a website, using TiddlyWiki 5 (Node.js version).
2. As PDF, via LaTeX.
  
Requires http://github.com/iani/tiddlywiki-render-template - and clones it automatically from within Emacs before the first export.

* /INCOMPLETE/

* TiddlyWiki

TiddlyWiki export and website publishing is implemented in the =org-pm-tw= library.  

The library defines one main interactive command, =org-pm-tw-deploy=, which exports a file or section to TiddlyWiki format, renders it to HTML, and then uploads the result as website to github.  This one command alone is sufficient to produce and update websites from any org-mode file or section.

Per default, org-mode files in a directory are exported per default to a directory called =WIKIS=, which is placed in the same directory as the org-mode source files.

To export only the current section, call =org-pm-tw-deploy= with a prefix-argument (=C-u=).

The first time that the command is called, it asks the user to input the name of the github account and repository and the name of the tiddlywiki to be created.  It stores the github account and repository url in a file "github.txt" to use as default for all future calls.

** Keyboard shortcuts: Meta-p p, r, e, u

I use the keyboard combination =Meta-p= (Alt-p, Opt-p or Esc-p) as prefix for the 3 interactive commands of the org-pm-tw library.  This is because (a) p is a mnemonic for "publish" and (b) it is not occupied by any other commands in Org mode, which is the only mode concerned.  Thus, the keyboard shortcuts are: 

- Meta-p d :: org-pm-tw-deploy 
- Meta-p p :: org-pm-tw-deploy (p for publish, alternative keyboard command for =org-pm-tw-deploy=)
- Meta-p r :: org-pm-tw-render
- Meta-p e :: org-pm-tw-export
- Meta-p u :: org-pm-tw-upload
- Meta-p t :: org-pm-tw-mark-tiddlers
- Meta-p l :: org-pm-latex-export (see section on latex below)

Preceding any of the above commands with the prefix argument shortcut (=C-u=) makes them work on the current section of the org-mode file, instead of the entire file. 

** Single Steps

For test purposes, the three steps /export/, /render/ and /upload/ can also be executed separately, although this is not necessary.

*** Export a file/section to a TiddlyWiki

*** Render a file/section to html

*** Upload all Wikis of this folder as site to github 

** How to specify which sections become tiddlers

Per default, each top level section of the org-mode document becomes a separate tiddler, while subsections of levels 2 or lower become subsections of the top-level tiddlers. 

However, it is possible to export subsections of level 2 or lower as independent tiddlers.  Such subsections will be incorporated in the tiddler of the section of which they are immediate children, and will be listed in a multi-level dynamically foldable menu in the main body of the tiddler. 

Subsections that are exported as Tiddlers are marked by setting the property =TIDDLER= in their properties block.  The value of this property indicates for which export the =TIDDLER= applies.  If the value is =t=, then the subsection will be exported as a Tiddler when the entire file is being exported.  If the value is a different string, then that string is used as an ID to identify the section for which the subsection must be exported as Tiddler (Only one subsection per Tiddler can be specified - TODO: store a list of values in the property to enable settings for more than one case per subtree).

The command for marking subsections as tiddlers is =org-pm-tw-mark-tiddlers=, and is bound to =Meta-p t=.  

- Meta-p t :: mark current section to be exported as separate tiddler
- Control-u Meta-p t :: Mark all subsections of relative depth 1 to be exported as tiddlers
- <Number prefix: n> Meta-p t :: Mark all subsections of relative depth n to be exported as tiddlers
- Meta-p T :: unmark current section - prevent from exporting as separate tiddler
- Control-u Meta-p T :: Unmark all subsections of relative depth 1 from being exported as tiddlers
- <Number prefix: n> Meta-p T :: Unmark all subsections of relative depth n from being exported as tiddlers

** How to specify the github repository for a folder



** Customize the look (style, theme) of the site
:PROPERTIES:
:DATE:     <2016-03-09 Wed 14:47>
:END:

The easiest way to customize is to open the wiki on a browser and use the built-in interface of TiddlyWiki.  To do this, open a terminal and do the following: 

1. Navigate to the directory of the wiki

For example: 

#+BEGIN_EXAMPLE
cd ./WIKIS/template
#+END_EXAMPLE

2. Run tiddlywiki on the server folder specifying a port number of your choice.

For example:

#+BEGIN_EXAMPLE
tiddlywiki server --server 8080
#+END_EXAMPLE

Choose a different port number for each wiki that you want to start while other wikis are already running.

** Test rendering a wiki with shell command

For testing purposes, you can try rendering a wiki to html from the command-line: 

1. Navigate to the directory of the wiki

For example: 

#+BEGIN_EXAMPLE
cd ./WIKIS/template
#+END_EXAMPLE

2. Run the render command of tiddlywiki specifying =rendered= as source directory and a directory of your choice as target directory.

For example:

#+BEGIN_EXAMPLE
tiddlywiki ./readonly --rendertiddler $:/core/save/all ../../../../rendered/render_test.html text/plain
#+END_EXAMPLE

** What is stored and where
:PROPERTIES: 
:DATE:     <2016-03-09 Wed 08:28>
:END:

- Each TiddlyWiki is stored as a subfolder inside the directory whose path is defined in custom variable =org-pm-wikis=.
- The default value of =org-pm-wikis= is "WIKIS".
- If the =org-pm-wikis= directory is a relative path such as "WIKIS", then the =org-pm-wikis= directory is created relative the directory that contains the org-mode source for the exported wiki.  In this way, each directory that contains org-mode files can be a group of wikis that are exported as html pages to form a website containing many pages. 
- The TiddlyWiki source of each wiki is stored in its own folder.
- The user is prompted to choose or enter the name of the folder before exporting.
- The name chosen by the user is stored in the org-mode source file to serve as default for future exports.
- The rendered TiddlyWiki html-export files of all Wikis are stored in a separate subdirectory of the =org-pm-wikis= folder, named =rendered=.
- The name of the rendered files is derived from the name of the directory of its wiki source.
- The entire =org-pm-wikis= directory is a git repository.
- The subdirectory =rendered= is used as root directory for the gh_pages branch of the git repository, so that the rendered wikis become html pages in the [[https://pages.github.com/][github-pages]] site of the git repository.
- Before exporting a file or section, prepare the directory of the org-source file by checking:
  - Does an =org-pm-wikis= subfolder exist? If not, make one.
  - Is the containing folder a git repository?  If not, make a repository and configure it to be a github-repository named after the name of the containing folder.  Also configure =rendered= subdirectory to be the root directory of the =gh_pages= branch.
  - This means that the github repository of an exported org-mode file will contain all 3 elements of the export process:
    1. The source code (in org-mode).
    2. The TiddlyWiki source code (in tiddler markup format, as single tiddlers, plus all accompanying config files and tiddlers)
    3. The rendered =html= file.

The structure of a repository folder containing org-mode source and wiki-exported sites is: 

#+BEGIN_EXAMPLE
index.org  # source files
page1.org
page2.org
WIKIS  # folder containing all export files
    index  # folders containing TiddlyWikis created from the org files
    page1
    page2
    rendered  # folder containing rendered html from the wikis
        index.html # Rendered html pages from the wikis
        page1.html
        page2.html
#+END_EXAMPLE

* PDF
:PROPERTIES:
:DATE:     <2016-03-09 Wed 14:45>
:END:

** Configuring latex for emacs


** Main command: org-pm-latex-export

Keyboard shortcut: Meta-p l

Calling the command with a prefix (C-u) exports the current section only.  Calling it without a prefix exports the entire file.

** Choosing templates


** Where export files are stored and how they are named
:PROPERTIES: 
:DATE:     <2016-03-09 Wed 08:28>
:END:

PDF exports are stored in the org-attachments directory

- Entire-file exports are saved in subdirectory "PDFs" of the attachments directory.  The PDF files are named after the name of the org-source file.
- Subtree exports are saved as regular attachments to the subtree's attachment dir.  The PDF file is named after the heading of the subtree, but the user is prompted to edit the file name in the minibuffer before starting the export.

